### ISSUE TITLE
Cannot connect to the Controller.

### ISSUE THREAD

**Issue by nexus1203** [PTriebold/MotomanConnector#4]
I am trying to connect to the DX200 controller on port 80 with the controller's IP address. However, I keep getting following error. 

```
self.s.connect((self.IP, self.PORT))
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
```

I can ping the machine and  can also connect to the High-Speed Ethernet (UDP) server without any issues. Do I need to change any setting in the controller to connect to the Ethernet sever?

**Comment by PTriebold** [comment]
Have you checked, that you are plugged into the correct ethernet jack? You should be plugged into CN104.
If you are, have checked the configuration of the Ethernet server? [EtherNet/IP COMMUNICATION FUNCTION
(FOR STANDARD LAN PORT)](http://assets.efc.gwu.edu/yaskawa-motoman/165838-1CD.pdf)
And lastly, maybe a stupid question, but have you tried power cycling the controller? It can sometimes happen, that something inside the controller crashes, resulting in the ethernet server becoming unresponsive

**Comment by nexus1203** [comment]
Yes, I am connecting to CN104, thats why I can also connect to the [High-Speed Ethernet Server](http://assets.efc.gwu.edu/yaskawa-motoman/165304-1CD.pdf). 
and for ethernet sever, I followed the documentation in [Ethernet Server Function for DX200](https://github.com/PTriebold/MotomanConnector/files/12168716/165984-1CD.pdf).
As for the configuration, I have set the IP address and other parameters as specified by the documentation. 
I have tried turning on and off several times too.  Using Nmap to scan the ports only shows port 21 and 23 as open. I wonder whats blocking the port 80 on this machine.

**Comment by PTriebold** [comment]
Sorry, we didn't have the high speed option, I assumed it would be on a separate module.

That is very strange. 

Just out of curiosity, have you tried port 23? Port 21 should be the ftp server.

**Comment by nexus1203** [comment]
I have tried the port 23, its the telnet port.

**Comment by PTriebold** [comment]
What is the IP of your PC?

**Comment by nexus1203** [comment]
its in the same range.
Controller is 192.168.1.2
PC is 192.168.1.10
Firewall is also disabled.

**Comment by PTriebold** [comment]
I cant't help you here... The Problem certainly lies in the controller, since the port is not even open. The only thing I can recommend short of phoning Yaskawa, is to make sure that the configuration is set and enabled. The manual I've linked is different than the one you've linked, so maybe check if you've done all the steps that are listed.
